// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// toggle //
// ------ //

#define toggle_wrap_target 0
#define toggle_wrap 1

static const uint16_t toggle_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xe000, //  1: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program toggle_program = {
    .instructions = toggle_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config toggle_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + toggle_wrap_target, offset + toggle_wrap);
    return c;
}

static inline void toggle_program_init(PIO pio, uint sm, uint offset, uint first_data_pin, float clk_div) {
    pio_gpio_init(pio, first_data_pin);
    pio_gpio_init(pio, first_data_pin+1);
    pio_sm_set_consecutive_pindirs(pio, sm, first_data_pin, 2, true);
    pio_sm_config c = toggle_program_get_default_config(offset);
    sm_config_set_out_pins(&c, first_data_pin, 2); // Pins affected by out
    sm_config_set_set_pins(&c, first_data_pin, 2); // Pins affected by set
    sm_config_set_clkdiv(&c, clk_div);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif
